# GitHub Pages Configuration

# Site settings
title: Terraform Spotify Provider
description: Create and manage Spotify playlists with Terraform
url: "https://ashrafxbilal.github.io/terraform-provider-spotify"
baseurl: "/terraform-provider-spotify"

# Build settings
markdown: kramdown
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme

# GitHub Pages settings
github:
  is_project_page: true
  repository_url: https://github.com/ashrafxbilal/terraform-provider-spotify
  owner_name: ashrafxbilal
  repository_name: terraform-provider-spotify

# Custom variables
show_downloads: true
google_analytics: # Add your Google Analytics tracking ID here if needed