name: Docker Build and Publish

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
    paths:
      - 'docker/Dockerfile'
      - 'docker/Dockerfile.dev'
      - '.github/workflows/docker-publish.yml'
  pull_request:
    paths:
      - 'docker/Dockerfile'
      - 'docker/Dockerfile.dev'
      - '.github/workflows/docker-publish.yml'
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Extract metadata for Docker
      - name: Extract Docker metadata for runtime image
        id: meta-runtime
        uses: docker/metadata-action@v4
        with:
          images: |
            docker.io/ashrafxbilal/terraform-spotify-provider
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=ref,event=branch
            type=ref,event=pr
            type=sha

      - name: Extract Docker metadata for dev image
        id: meta-dev
        uses: docker/metadata-action@v4
        with:
          images: |
            docker.io/ashrafxbilal/terraform-spotify-provider-dev
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=ref,event=branch
            type=ref,event=pr
            type=sha

      # Build and push runtime image
      - name: Build and push runtime Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-runtime.outputs.tags }}
          labels: ${{ steps.meta-runtime.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Build and push dev image
      - name: Build and push dev Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.dev
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-dev.outputs.tags }}
          labels: ${{ steps.meta-dev.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max