name: Build Playlist

on:
  schedule:
    # Run at 8:00 AM UTC every day
    # - cron: '0 8 * * *'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  refresh-playlists:
    name: Getting Your Weather and Mood Updates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Build and install provider
        run: |
          go build -o terraform-provider-spotify
          mkdir -p ~/.terraform.d/plugins/registry.terraform.io/ashrafxbilal/spotify/0.1.0/linux_amd64
          cp terraform-provider-spotify ~/.terraform.d/plugins/registry.terraform.io/ashrafxbilal/spotify/0.1.0/linux_amd64/

      - name: Set up environment variables
        run: |
          echo "TF_VAR_spotify_client_id=${{ secrets.SPOTIFY_CLIENT_ID }}" >> $GITHUB_ENV
          echo "TF_VAR_spotify_client_secret=${{ secrets.SPOTIFY_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "TF_VAR_spotify_redirect_uri=${{ secrets.SPOTIFY_REDIRECT_URI }}" >> $GITHUB_ENV
          echo "TF_VAR_spotify_refresh_token=${{ secrets.SPOTIFY_REFRESH_TOKEN }}" >> $GITHUB_ENV
  

      - name: Initialize Terraform
        run: |
          cd docs/examples/basic_playlist
          terraform init

      - name: Apply Terraform
        run: |
          cd docs/examples/basic_playlist
          terraform apply -auto-approve

      - name: Log refresh completion
        run: echo "Playlist refresh completed at $(date)"